### ISSUE TITLE
Signed assembly

### ISSUE THREAD

**Issue by usmanatron** [schourode/iso3166#12]
IT would be great if the assembly could be signed (so it can be used in projects that are also signed).
More than happy to make these changes and submit a PR.  Just wanted to know what your thoughts are first?

**Comment by andersnm** [comment]
Good idea. I would merge it!

**Comment by usmanatron** [comment]
Thanks @andersnm , Ill have a go!

**Comment by andersnm** [comment]
@usmanatron  FYI this has been fixed. Next release will have a signed assembly
