### ISSUE TITLE
Change license?

### ISSUE THREAD

**Issue by andersnm** [schourode/iso3166#14]
@schourode  

Would you mind if we changed the license of the project to MIT? 

I guess the original reason for choosing CC-BY-SA-3.0 is because the data was originally sourced from Wikipedia. But now we changed to using the official ISO registry for sourcing, so one could make an argument it is acceptable to change the license also. 

I'm asking is because Nuget rejects the upload after adding license metadata to the package:

"License expression must only contain licenses that are approved by Open Source Initiative or Free Software Foundation. Unsupported licenses: CC-BY-SA-3.0."

This page has a table with licenses, including CC-BY-*, and whether they are approved:
https://spdx.org/licenses/

(Although I could also not tell Nuget about the license to get past the block)

**Comment by schourode** [comment]
@andersnm Good to hear that this library is still in active use and in good hands 😄 

As for the part of the library that was created by myself (the application code), I am totally fine with releasing that under the MIT license. If using the ISO list itself as a data source can impose any restrictions of license, I am afraid I can offer no advise.
