### ISSUE TITLE
Separate out the Northern Ireland(XI) country from Great Britain

### ISSUE THREAD

**Issue by prashantavalara** [schourode/iso3166#18]
New Brexit legislation changes state that Northern Ireland will be considered a separate country from Great Britain. As a result, Northern Ireland will have its own country ISO code XI. Is there any plan to add a country code for  Northern Ireland(XI)?

**Comment by kristoftorfs** [comment]
Would also be nice if this could at least be backported to 3.x versions.

**Comment by jonathanrelf** [comment]
Given this library follows the ISO 3166 standard, then it would only make sense to support this once the standard has changed. The current listing hasn't been updated since 2020: https://www.iso.org/obp/ui/#iso:code:3166:GB
