### ISSUE TITLE
Missing Country 

### ISSUE THREAD

**Issue by onesyndrome** [schourode/iso3166#20]
Missing country from the list
"Netherlands Antilles", 
Alpha2 = "AN",
 Alpha3 = "ANT", 
 NumericCode = "530"`

**Comment by 304NotModified** [comment]
ANT is **Transitionally reserved** and not **Officially assigned**

See https://www.iso.org/obp/ui/#search

![image](https://user-images.githubusercontent.com/5808377/158380722-e189896b-086c-4fcd-b479-2b81b2fddf5d.png)

**Comment by onesyndrome** [comment]
Got it, thanks
