### ISSUE TITLE
Enable Deterministic build and Source Link

### ISSUE THREAD

**Issue by 304NotModified** [schourode/iso3166#23]
Please enable Deterministic build and Source Link

> Deterministic builds are important as they enable verification that the resulting binary was built from the specified source and provides traceability.

https://github.com/clairernovotny/DeterministicBuilds

See:
https://nuget.info/packages/ISO3166/1.0.3

![image](https://user-images.githubusercontent.com/5808377/158379780-6a74066d-4c56-4b32-8893-6136f4ea26c4.png)

**Comment by schourode** [comment]
I am not currently doing much .NET development, and I am not up to speed on the packaging system. Your suggestions sounds reasonable though. Is this something you would be able to put together a pull request for?

**Comment by 304NotModified** [comment]
I will create a pr. But perhaps it takes some time, as I'm almost on holiday!

**Comment by 304NotModified** [comment]
Found some time :) --> #25
