### ISSUE TITLE
Packages for .NET Core

### ISSUE THREAD

**Issue by andersnm** [schourode/iso3166#5]
Any chance we can have nuget packages for this library targeting .NET Core

**Comment by andersnm** [comment]
A project.json could look like this. It replaces the csproj and nuspec. Build with VS2015 with latest updates and tools for .NET Core to get a super portable nuget package targeting net20 and netstandard1.0. 

Is it worth making a PR? Is the project alive?

```
{
  "packOptions": {
    "tags": [ "iso3166", "country" ],
    "projectUrl": "https://github.com/schourode/iso3166",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "summary": "List of countries including their official English name as well as their ISO 3166 defined two-letter, three-letter and three-digit country codes.",
    "requireLicenseAcceptance": false
  },
  "title" : "ISO3166",
  "version": "1.0.2-dev",
  "description": "ISO 3166-1 is part of the ISO 3166 standard published by the International Organization for Standardization (ISO), and defines codes for the names of countries, dependent territories, and special areas of geographical interest.\nThis package provides a list of countries including their official English name as well as their ISO 3166 defined two-letter, three-letter and three-digit country codes. The list is accessible for any .NET language via the static field ISO3166.Country.List.\nData source: Wikipedia.",
  "authors": [ "Jørn Schou-Rode" ],
  "frameworks": {
    "net20": {},
    "netstandard1.0": {
      "dependencies": {
        "System.Runtime": "4.1.0"
      }
    }
  },
  "scripts": {
    "postcompile": "dotnet pack --no-build --configuration %compile:Configuration%"
  }
}

```

**Comment by niemyjski** [comment]
@schourode is there any plans to add support for .net standard.

**Comment by schourode** [comment]
@niemyjski I don't plan to do any changes to this myself, but if you care to do the changes (I believe the JSON version above is now outdated due to changes to the build system), I would be happy to merge the pull request and push a new version of the package to NuGet.

**Comment by schourode** [comment]
@andersnm Any chance you would be interested in helping out with getting #8 pushed to Nuget? I have not done much work in .NET land these past years, and as a result, I am not up-to-date on how to work with the package system.

Your changes looks legit. If you are willing to help out with this, I would be happy to grant you push whatever access needed in Github and NuGet, making you the second core team member of the iso3166 .net package 😄

**Comment by andersnm** [comment]
@schourode Sure, I'd be happy to help out. Please add me as a collaborator here on Github, and as a package admin on nuget.org. I'm [andersnm](https://www.nuget.org/profiles/andersnm) on nuget.org too

**Comment by schourode** [comment]
@andersnm Done and done. Welcome on board 😃

**Comment by andersnm** [comment]
@schourode Takk! I've accepted both invitations. Will try and find the time to merge and upload later this week.

**Comment by harrybellamy** [comment]
I was about to do this conversion myself until I noticed someone else was doing it, thanks guys.

**Comment by andersnm** [comment]
@schourode, I've set up Appveyor to build the project and create the nupkg, but it does not build automatically. I believe the project admin has to configure the webhook. Can you please setup per this article: https://help.appveyor.com/discussions/questions/2272-github-webhook-deleted-how-to-recreate

Our webhook URL is:
https://ci.appveyor.com/api/github/webhook?id=66cq4fj631xk6isp

**Comment by schourode** [comment]
@andersnm Automated deployment, yay! I'll add the webhook right away.

**Comment by Apocryph** [comment]
Hi @schourode - any word on when this will be available?  I was keeping track of this thread, but I haven't seen anything new on nuget yet.

Thanks for the work on the conversion, guys!

**Comment by andersnm** [comment]
@Apocryph Thanks for following up. Just uploaded now:

https://www.nuget.org/packages/ISO3166/1.0.2

**Comment by Apocryph** [comment]
Thanks @schourode and @andersnm!
