### ISSUE TITLE
Strongly typed

### ISSUE THREAD

**Issue by cyberprune** [schourode/iso3166#7]
Can you please sign the binary, I wanted to use this library in a solution with Code Analysis, but it doesn't have a strongly typed dll.

**Comment by schourode** [comment]
Sorry about not getting back to you. I have completely missed this issue until now. Seeing that this is now ~1 year old, I am guessing you found another solution. I will close this now, but feel free to object if you still need this.

**Comment by cyberprune** [comment]
No worries, we ended up creating a copy of the solution, adding a key and creating a private build for it.
