### ISSUE TITLE
Vietnam

### ISSUE THREAD

**Issue by redzmey** [schourode/iso3166#9]
wikipedia has invalid name for Vietnam. It's not Viet Nam
https://en.wikipedia.org/wiki/Vietnam

**Comment by jelizaga3-gatech** [comment]
The country code is correct according to Wikipedia, see:

>The International Organization for Standardization (ISO) uses the United Nations (UN) country name Viet Nam for Vietnam.

https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes#cite_note-40
